export const mockVideos = [
  {
    id: 1,
    type: "long",
    user: {
      name: "Tech Creator",
      username: "@techcreator",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    title: "Building a Startup from Scratch - Complete Guide",
    description: "Learn how to build a successful startup from the ground up, covering everything from idea validation to funding and scaling. This comprehensive guide will walk you through every step of the process, from ideation to launch.",
    community: "Startup Community",
    series: "Entrepreneur Series",
    episodes: [
      { id: 1, videoURL: "/MockVideos/video.mp4" },
      { id: 2, videoURL: "/MockVideos/video2.mp4" },
      { id: 3, videoURL: "/MockVideos/video3.mp4" },
      { id: 4, videoURL: "/MockVideos/video4.mp4" },
    ],
    currentEpisode: 1,
    duration: "15:42",
    progress: 35,
    likes: 89500,
    comments: 892,
    shares: 234,
    earnings: 1200,
    videoUrl: "/MockVideos/video.mp4",
  },
  {
    id: 2,
    type: "long",
    user: {
      name: "Code Master",
      username: "@codemaster",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    title: "React vs Next.js - Which Should You Choose?",
    description: "Complete comparison of React and Next.js frameworks, diving deep into their features, performance, and best use cases for modern web development. This is a very comprehensive guide, perfect for developers looking to make informed decisions.",
    community: "Developer Community",
    series: "Web Dev Masterclass",
    episodes: [
      { id: 1, videoURL: "/MockVideos/video2.mp4" },
      { id: 2, videoURL: "/MockVideos/video.mp4" },
      { id: 3, videoURL: "/MockVideos/video4.mp4" },
      { id: 4, videoURL: "/MockVideos/video3.mp4" },
      { id: 5, videoURL: "/MockVideos/video2.mp4" },
    ],
    currentEpisode: 1,
    duration: "22:15",
    progress: 60,
    likes: 67000,
    comments: 445,
    shares: 123,
    earnings: 890,
    videoUrl: "/MockVideos/video.mp4",
  },

  {
    id: 3,
    type: "short",
    user: {
      name: "Code Master",
      username: "@codemaster",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    title: "React vs Next.js - Which Should You Choose?",
    description: "Complete comparison of React and Next.js frameworks, diving deep into their features, performance, and best use cases for modern web development. This is a very comprehensive guide, perfect for developers looking to make informed decisions.",
    community: "Developer Community",
    duration: "22:15",
    progress: 60,
    likes: 6700,
    comments: 4450,
    shares: 127,
    earnings: 899,
    videoUrl: "/MockVideos/video3.mp4",
  },

  {
    id: 4,
    type: "short",
    user: {
      name: "Code Master",
      username: "@codemaster",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    title: "React vs Next.js - Which Should You Choose?",
    description: "Complete comparison of React and Next.js frameworks, diving deep into their features, performance, and best use cases for modern web development. This is a very comprehensive guide, perfect for developers looking to make informed decisions.",
    community: "Developer Community",
    duration: "22:15",
    progress: 60,
    likes: 6680,
    comments: 745,
    shares: 673,
    earnings: 190,
    videoUrl: "/MockVideos/video4.mp4",
  },
]